```{r echo = FALSE}
library(knitr)

# Color text
colorize <- function(x, color) {
  
  if (knitr::is_latex_output()) {
    
    sprintf("\\textcolor{%s}{%s}", color, x)
    
  } else if (knitr::is_html_output()) {
    
    sprintf("<span style='color: %s;'>%s</span>", color, x)
    
  } else { x }
}
```

# Profundizando tidyverse: elecciones y Spotify {#tidyverse-2}

:::: {.blackbox data-latex=""}

Scripts usados:

* [**script20.R**](https://github.com/dadosdelaplace/courses-ECI-2022/blob/main/scripts/script20.R): profundizando tidyverse.  Ver en <https://github.com/dadosdelaplace/courses-ECI-2022/blob/main/scripts/script20.R>

::::


## Depurando datos de elecciones

```{r eval = FALSE}
library(rvest)
wiki <-
  paste0("https://en.wikipedia.org/wiki/Opinion_polling_for_the_next_Spanish_general_election")
html <- read_html(wiki)
tablas <- html_nodes(html, ".wikitable")
encuestas_2022 <- html_table(tablas[[1]], header = FALSE)
encuestas_2022 <- encuestas_2022 %>% slice(-(1:2))
encuestas_2021 <- html_table(tablas[[2]], header = FALSE)
encuestas_2021 <- encuestas_2021 %>% slice(-(1:2))

encuestas <- rbind(encuestas_2022, encuestas_2021)
names(encuestas) <-
  c("casa", "fechas", "muestra", "participacion", "PSOE", "PP",	"Vox",
    "UP", "Cs", "ERC", "MP", "JxCat",	"PNV",	"EHBildu", "CUP",
    "CC", "BNG", "NA+", "PRC", "EV", "ventaja")


encuestas %>%
  # Quitamos "," en números
  mutate_at(vars(contains(c("Muestra"))),
            function(x) { gsub(",", "", x) }) %>%
  mutate(participacion = gsub("?", NA, participacion)) %>%
  # Convertimos a números salvo casa y muestra
  mutate_at(vars(!contains(c("casa", "fechas"))), as.numeric) %>% 
  # Convertimos a fecha
  mutate_at(vars(contains(c("fechas"))),
            function(x) { 
              dmy(map_chr(str_split(
                map_chr(str_split(x, " "),
                        function (y) { paste0(y, collapse = " ") }), "–"),
                function(z) { z[-1] })) }) %>%
  # Limpiamos nombre encuestas
  mutate_at(vars(contains(c("casa"))),
            function(x) { toupper(map_chr(str_split(x, "\\["),
                                          function (y) { y[1] } )) })
```

## Depurando datos de Spotify

b
