<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Capítulo 25 Resumiendo y relacionado datos | Analizando datos, visualizando información, contando historias</title>
<meta name="author" content="Javier Álvarez Liébana y Gabriel Valverde Castilla">
<meta name="description" content="Scripts usados: script25.R: resumiendo y relacionando datos. Ver en https://github.com/dadosdelaplace/courses-ECI-2022/blob/main/scripts/script25.R  Ahora que ya sabemos depurar y transformar los...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Capítulo 25 Resumiendo y relacionado datos | Analizando datos, visualizando información, contando historias">
<meta property="og:type" content="book">
<meta property="og:image" content="/img/logo_R.png">
<meta property="og:description" content="Scripts usados: script25.R: resumiendo y relacionando datos. Ver en https://github.com/dadosdelaplace/courses-ECI-2022/blob/main/scripts/script25.R  Ahora que ya sabemos depurar y transformar los...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Capítulo 25 Resumiendo y relacionado datos | Analizando datos, visualizando información, contando historias">
<meta name="twitter:description" content="Scripts usados: script25.R: resumiendo y relacionando datos. Ver en https://github.com/dadosdelaplace/courses-ECI-2022/blob/main/scripts/script25.R  Ahora que ya sabemos depurar y transformar los...">
<meta name="twitter:image" content="/img/logo_R.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><link href="libs/_Sen-0.4.0/font.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=DM%20Mono&amp;display=swap" rel="stylesheet">
<link href="libs/_Bitter-0.4.0/font.css" rel="stylesheet">
<script src="libs/bs3compat-0.3.0/transition.js"></script><script src="libs/bs3compat-0.3.0/tabs.js"></script><script src="libs/bs3compat-0.3.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script><link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="libs/datatables-binding-0.18/datatables.js"></script><link href="libs/dt-core-1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="libs/dt-core-1.10.20/js/jquery.dataTables.min.js"></script><link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet">
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script><link href="libs/wordcloud2-0.0.1/wordcloud.css" rel="stylesheet">
<script src="libs/wordcloud2-0.0.1/wordcloud2-all.js"></script><script src="libs/wordcloud2-0.0.1/hover.js"></script><script src="libs/wordcloud2-binding-0.2.1/wordcloud2.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="css/style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Analizando datos, visualizando información, contando historias</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Prefacio</a></li>
<li class="book-part">Recursos</li>
<li><a class="" href="ejercicios-recopilados.html">📝 Ejercicios recopilados</a></li>
<li><a class="" href="recursos-de-aprendizaje.html">📚 Recursos de aprendizaje</a></li>
<li><a class="" href="pr%C3%A1cticas-evaluables.html">🏅 Prácticas evaluables</a></li>
<li class="book-part">Toma de contacto</li>
<li><a class="" href="requisitos.html"><span class="header-section-number">1</span> Requisitos</a></li>
<li><a class="" href="instalacion.html"><span class="header-section-number">2</span> Instalación</a></li>
<li><a class="" href="que-es-R.html"><span class="header-section-number">3</span> ¿Qué es R?</a></li>
<li><a class="" href="primeros-pasos.html"><span class="header-section-number">4</span> Primeros pasos</a></li>
<li class="book-part">Conceptos básicos</li>
<li><a class="" href="tipos-datos.html"><span class="header-section-number">5</span> Tipos de datos</a></li>
<li><a class="" href="vectores.html"><span class="header-section-number">6</span> Vectores</a></li>
<li><a class="" href="operacionesvectores.html"><span class="header-section-number">7</span> Operaciones con vectores</a></li>
<li><a class="" href="datos.html"><span class="header-section-number">8</span> Datos estructurados</a></li>
<li><a class="" href="repaso-1.html"><span class="header-section-number">9</span> Repaso: empezando a trastear con datos</a></li>
<li class="book-part">Haciendo el trabajo más fácil</li>
<li><a class="" href="if-else.html"><span class="header-section-number">10</span> Estructuras de control: if-else</a></li>
<li><a class="" href="bucles.html"><span class="header-section-number">11</span> Estructuras de control: bucles</a></li>
<li><a class="" href="proyecto.html"><span class="header-section-number">12</span> Primer proyecto de trabajo</a></li>
<li><a class="" href="funciones.html"><span class="header-section-number">13</span> Funciones</a></li>
<li><a class="" href="listas.html"><span class="header-section-number">14</span> Listas</a></li>
<li class="book-part">Empezando a explorar datos</li>
<li><a class="" href="tibble.html"><span class="header-section-number">15</span> Mejorando los data.frame: datos tibble</a></li>
<li><a class="" href="tidy.html"><span class="header-section-number">16</span> Tidy vs messy data: daticos ordenados</a></li>
<li><a class="" href="importar-exportar.html"><span class="header-section-number">17</span> Sacando datos de las piedras</a></li>
<li><a class="" href="rmarkdown.html"><span class="header-section-number">18</span> Contando los datos: rmarkdown</a></li>
<li class="book-part">Incursión a tidyverse</li>
<li><a class="" href="tidyverse.html"><span class="header-section-number">19</span> Depuración y transformación</a></li>
<li><a class="" href="tidyverse-2.html"><span class="header-section-number">20</span> Profundizando tidyverse: encuestas electorales</a></li>
<li><a class="" href="ggplot2.html"><span class="header-section-number">21</span> Visualizando datos: incursión a ggplot2</a></li>
<li><a class="" href="ggplot2_plus.html"><span class="header-section-number">22</span> Profundizando en ggplot2</a></li>
<li class="book-part">Incursión a la estadística descriptiva</li>
<li><a class="" href="descriptiva_cualitativas.html"><span class="header-section-number">23</span> Extrayendo información: estadística descriptiva con cualitativas</a></li>
<li><a class="" href="descriptiva_cuantitativas.html"><span class="header-section-number">24</span> Extrayendo información: estadística descriptiva con cuantitativas continuas</a></li>
<li><a class="active" href="resumenes.html"><span class="header-section-number">25</span> Resumiendo y relacionado datos</a></li>
<li><a class="" href="bibliograf%C3%ADa.html">Bibliografía</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/dadosdelaplace/courses-ECI-2022">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="resumenes" class="section level1">
<h1>
<span class="header-section-number">Capítulo 25</span> Resumiendo y relacionado datos<a class="anchor" aria-label="anchor" href="#resumenes"><i class="fas fa-link"></i></a>
</h1>
<div class="blackbox">
<p>Scripts usados:</p>
<ul>
<li>
<a href="https://github.com/dadosdelaplace/courses-ECI-2022/blob/main/scripts/script25.R"><strong>script25.R</strong></a>: resumiendo y relacionando datos. Ver en <a href="https://github.com/dadosdelaplace/courses-ECI-2022/blob/main/scripts/script25.R" class="uri">https://github.com/dadosdelaplace/courses-ECI-2022/blob/main/scripts/script25.R</a>
</li>
</ul>
</div>
<p>Ahora que <strong>ya sabemos depurar y transformar los datos</strong>, y algunas de las características de los tipos de variables, en esta sección vamos a aprender dos cosas básicas a la hora de trabajar con datos:</p>
<ul>
<li>Realizar <mark><strong>resúmenes numéricos</strong></mark> de los datos, de forma general pero también cuando queremos calcular estadísticas desagregadas por grupos.</li>
<li><mark><strong>Medidas de centralización, dispersión y posición</strong></mark></li>
<li>
<mark><strong>Relacionar tablas</strong></mark> entre sí (los famosos <em>join</em>).</li>
</ul>
<div id="resúmenes-numéricos-summarise-y-skimr-y-por-grupos-group_by" class="section level2">
<h2>
<span class="header-section-number">25.1</span> Resúmenes numéricos (summarise y skimr) y por grupos (group_by)<a class="anchor" aria-label="anchor" href="#res%C3%BAmenes-num%C3%A9ricos-summarise-y-skimr-y-por-grupos-group_by"><i class="fas fa-link"></i></a>
</h2>
<p>Antes de pasar a ver <strong>cómo generar nuestras propias estadísticas de los datos</strong>, veamos la funcionalidad de un maravilloso paquete llamado <a href="https://docs.ropensci.org/skimr/">skimr</a>, que nos permite tener en un vistazo un <mark><strong>resumen numérico</strong></mark> muy completo de nuestros datos, con <strong>histograma/diagrama de barras incluido</strong>.</p>
<div class="sourceCode" id="cb2145"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://docs.ropensci.org/skimr/">skimr</a></span><span class="op">)</span>
<span class="va">starwars</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://docs.ropensci.org/skimr/reference/skim.html">skim</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<caption>
<span id="tab:unnamed-chunk-882">Tabla 25.1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">Piped data</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">87</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">14</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">8</td>
</tr>
<tr class="odd">
<td align="left">list</td>
<td align="left">3</td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">3</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table></div>
<p><strong>Variable type: character</strong></p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">name</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">3</td>
<td align="right">21</td>
<td align="right">0</td>
<td align="right">87</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">hair_color</td>
<td align="right">5</td>
<td align="right">0.94</td>
<td align="right">4</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">12</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">skin_color</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">3</td>
<td align="right">19</td>
<td align="right">0</td>
<td align="right">31</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">eye_color</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">3</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">15</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">sex</td>
<td align="right">4</td>
<td align="right">0.95</td>
<td align="right">4</td>
<td align="right">14</td>
<td align="right">0</td>
<td align="right">4</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">gender</td>
<td align="right">4</td>
<td align="right">0.95</td>
<td align="right">8</td>
<td align="right">9</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">homeworld</td>
<td align="right">10</td>
<td align="right">0.89</td>
<td align="right">4</td>
<td align="right">14</td>
<td align="right">0</td>
<td align="right">48</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">species</td>
<td align="right">4</td>
<td align="right">0.95</td>
<td align="right">3</td>
<td align="right">14</td>
<td align="right">0</td>
<td align="right">37</td>
<td align="right">0</td>
</tr>
</tbody>
</table></div>
<p><strong>Variable type: list</strong></p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">n_unique</th>
<th align="right">min_length</th>
<th align="right">max_length</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">films</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">24</td>
<td align="right">1</td>
<td align="right">7</td>
</tr>
<tr class="even">
<td align="left">vehicles</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">11</td>
<td align="right">0</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="left">starships</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">17</td>
<td align="right">0</td>
<td align="right">5</td>
</tr>
</tbody>
</table></div>
<p><strong>Variable type: numeric</strong></p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">height</td>
<td align="right">6</td>
<td align="right">0.93</td>
<td align="right">174.36</td>
<td align="right">34.77</td>
<td align="right">66</td>
<td align="right">167.0</td>
<td align="right">180</td>
<td align="right">191.0</td>
<td align="right">264</td>
<td align="left">▁▁▇▅▁</td>
</tr>
<tr class="even">
<td align="left">mass</td>
<td align="right">28</td>
<td align="right">0.68</td>
<td align="right">97.31</td>
<td align="right">169.46</td>
<td align="right">15</td>
<td align="right">55.6</td>
<td align="right">79</td>
<td align="right">84.5</td>
<td align="right">1358</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">birth_year</td>
<td align="right">44</td>
<td align="right">0.49</td>
<td align="right">87.57</td>
<td align="right">154.69</td>
<td align="right">8</td>
<td align="right">35.0</td>
<td align="right">52</td>
<td align="right">72.0</td>
<td align="right">896</td>
<td align="left">▇▁▁▁▁</td>
</tr>
</tbody>
</table></div>
<p>Dicho resumen nos proporciona:</p>
<ul>
<li><p>Variables de tipo <strong>caracter</strong>: <code>n_missing</code> (número de ausentes), <code>complete_rate</code> (proporción de datos sin ausentes), <code>min/max</code> y <code>n_unique</code> (número de valores únicos).</p></li>
<li><p>Variables de tipo <strong>lista</strong>: <code>n_missing</code> (número de ausentes), <code>complete_rate</code> (proporción de datos sin ausentes), <code>n_unique</code> (número de valores únicos) y <code>min_length/max_length</code> (longitud mínimo/máxima de las listas).</p></li>
<li><p>Variables de tipo <strong>numérico</strong>: <code>n_missing</code> (número de ausentes), <code>complete_rate</code> (proporción de datos sin ausentes), <code>mean/sd</code> (media y cuasidesviación típica), <code>p0/p25/p50/p75/p100</code> (cuartiles, percentiles 0%-25%-50%-75%-100%, valores que nos dividen nuestro conjunto en 4 trozos) e <code>hist</code> (una especie de histograma/barras sencillo).</p></li>
</ul>
<p>Este resumen no solo podemos visualizarlo sino que podemos guardarlo para exportarlo por ejemplo en un <code>.csv</code>. Sin embargo, aunque el resumen es bastante completo, muchas veces querremos <mark><strong>generar nuestras propias estadísticas o resúmenes numéricos</strong></mark>, y para eso vamos a aplicar <code><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise()</a></code>, que nos calculará estadísticas de nuestros datos.</p>
<div id="medidas-de-centralización-y-dispersión" class="section level3">
<h3>
<span class="header-section-number">25.1.1</span> Medidas de centralización y dispersión<a class="anchor" aria-label="anchor" href="#medidas-de-centralizaci%C3%B3n-y-dispersi%C3%B3n"><i class="fas fa-link"></i></a>
</h3>
<p>Por ejemplo, vamos a <mark><strong>calcular las medidas de centralización (media-mediana-moda)</strong></mark>. Para la media y la mediana basta con usar las funciones correspondientes <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code> y <code><a href="https://rdrr.io/r/stats/median.html">median()</a></code>, dentro de <code><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise()</a></code></p>
<div class="sourceCode" id="cb2146"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise</a></span><span class="op">(</span>media <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mass</span><span class="op">)</span>,
                       mediana <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">mass</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   media mediana
##   &lt;dbl&gt;   &lt;dbl&gt;
## 1    NA      NA</code></pre>
<p>Al contrario que las demás órdenes de <a href="https://tidyverse.tidyverse.org">tidyverse</a>, la función <code><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise()</a></code> no nos devuelve la tabla original modificada, sino un resumen de los datos, con las funciones que le hayamos indicdo. Como ves nos <strong>devuelve un dato ausente</strong> ya que al existir datos ausentes en la variables, <strong>la media también lo es</strong>. Para evitar ese problema <strong>podemos hacer dos cosas</strong>: eliminar antes los ausentes, o indicarle en la propia media y mediana que haga el cálculo ignorando los valores <code>NA</code>.</p>
<div class="sourceCode" id="cb2148"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Primero eliminamos NA</span>
<span class="va">starwars</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/pkg/tidyr/man/drop_na.html">drop_na</a></span><span class="op">(</span><span class="va">mass</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise</a></span><span class="op">(</span>media <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mass</span><span class="op">)</span>, mediana <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">mass</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   media mediana
##   &lt;dbl&gt;   &lt;dbl&gt;
## 1  97.3      79</code></pre>
<div class="sourceCode" id="cb2150"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Al realizar el cálculo los ignora</span>
<span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise</a></span><span class="op">(</span>media <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            mediana <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   media mediana
##   &lt;dbl&gt;   &lt;dbl&gt;
## 1  97.3      79</code></pre>
<p>Las <mark><strong>medidas de centralización</strong></mark> son aquellos parámetros o valores que nos informe en torno a que <mark><strong>valores</strong></mark> se concentran los datos. La <mark><strong>media</strong></mark><span class="math inline">\(\overline{x}\)</span> es una medida de centralización basada en el valor que nos <strong>minimiza el promedio de desviaciones al cuadrado</strong>: la media es el valor que está más cerca de todos los puntos a la vez (con la distancia Euclídea, definida como la diferencia al cuadrado)</p>
<p><span class="math display">\[\overline{x} = \frac{1}{N} \sum_{i=1}^{N} x_i, \qquad \overline{x} = \arg \min_{x} \frac{1}{N} \sum_{i=1}^{N} \left(x_i - x \right)^2\]</span></p>
<p>La media <mark><strong>solo se puede calcular para variables cuantitativas</strong></mark>: solo podemos calcular medias de números.</p>
<div class="sourceCode" id="cb2152"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Media de todas las cuantitativas</span>
<span class="va">starwars_nueva</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise</a></span><span class="op">(</span>media <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/across.html">across</a></span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span>, <span class="va">mean</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   media$height $mass $birth_year $n_films
##          &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;
## 1         174.  97.3        87.6     1.99</code></pre>
<p> </p>
<p>La <mark><strong>mediana</strong></mark> se define como el valor que ocupa el <mark><strong>centro de los datos cuando los ordenamos de menor a mayor</strong></mark>, un valor que nos deja por debajo al menos el 50% y por encima al menos el 50%.</p>
<div class="sourceCode" id="cb2154"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Media y mediana de todas las cuantitativas</span>
<span class="va">starwars_nueva</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise</a></span><span class="op">(</span>media <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/across.html">across</a></span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span>, <span class="va">mean</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            mediana <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/across.html">across</a></span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span>, <span class="va">median</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   media$height $mass $birth_year $n_films mediana$height $mass $birth_year
##          &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;          &lt;int&gt; &lt;dbl&gt;       &lt;dbl&gt;
## 1         174.  97.3        87.6     1.99            180    79          52</code></pre>
<p>La mediana también se puede calcular para <mark><strong>variables cualitativas ordinales (categorías que se puedan ordenar)</strong></mark>, además de para variables cuantitativas.. Vamos a construir una variable que sea «muy bajo-bajo-medio-alto-muy alto» según la estatura, y calcular la mediana para dichas categorías.</p>
<div class="sourceCode" id="cb2156"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">categorias</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"muy bajo"</span>, <span class="st">"bajo"</span>, <span class="st">"medio"</span>, <span class="st">"alto"</span>, <span class="st">"muy alto"</span><span class="op">)</span>
<span class="va">starwars_talla</span> <span class="op">&lt;-</span> 
  <span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/mutate.html">mutate</a></span><span class="op">(</span>talla <span class="op">=</span>
           <span class="fu"><a href="https://rdrr.io/r/base/cut.html">cut</a></span><span class="op">(</span><span class="va">height</span>, breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="cn">Inf</span>, <span class="fl">80</span>, <span class="fl">120</span>, <span class="fl">160</span>, <span class="fl">190</span>, <span class="cn">Inf</span><span class="op">)</span>,
               labels <span class="op">=</span> <span class="va">categorias</span><span class="op">)</span><span class="op">)</span>

<span class="co"># Mediana (hay que pasárselo como número)</span>
<span class="va">starwars_talla</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise</a></span><span class="op">(</span>mediana <span class="op">=</span>
              <span class="va">categorias</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">talla</span><span class="op">)</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">]</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   mediana
##   &lt;chr&gt;  
## 1 alto</code></pre>
<p>Para la <strong>moda tenemos algún problema mayor</strong> ya que no hay un función en los paquetes <code>{base}</code> para su cálculo directo. La <mark><strong>moda</strong></mark> se define como el <mark><strong>valor más repetido</strong></mark>: si tenemos algo discreto o cualitativo es la barra más alta.</p>
<div class="sourceCode" id="cb2158"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>

<span class="co"># Carga</span>
<span class="va">netflix</span> <span class="op">&lt;-</span>
  <span class="fu"><a href="https://rdrr.io/pkg/readr/man/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">'https://raw.githubusercontent.com/elartedeldato/datasets/main/netflix_titles.csv'</span><span class="op">)</span>

<span class="co"># Películas y series de insti</span>
<span class="va">netflix_hs</span> <span class="op">&lt;-</span> <span class="va">netflix</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/stringr/man/str_detect.html">str_detect</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/chartr.html">toupper</a></span><span class="op">(</span><span class="va">description</span><span class="op">)</span>, <span class="st">"HIGH SCHOOL"</span><span class="op">)</span><span class="op">)</span>
<span class="va">netflix_hs</span> </code></pre></div>
<pre><code>## # A tibble: 150 × 12
##    show_id type  title   director cast    country date_added release_year rating
##    &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;             &lt;dbl&gt; &lt;chr&gt; 
##  1 s8      Movie 187     Kevin R… Samuel… United… November …         1997 R     
##  2 s32     Movie #Frien… Rako Pr… Adipat… Indone… May 21, 2…         2018 TV-G  
##  3 s34     Movie #reali… Fernand… Nesta … United… September…         2017 TV-14 
##  4 s47     Movie 1 Chan… Adam De… Lexi G… United… July 1, 2…         2014 TV-PG 
##  5 s48     Movie 1 Mile… Leif Ti… Billy … United… July 7, 2…         2017 TV-14 
##  6 s56     Movie 100 Th… &lt;NA&gt;     Isabel… United… November …         2014 TV-Y  
##  7 s58     Movie 100% H… Jastis … Anisa … Indone… January 7…         2020 TV-14 
##  8 s148    Movie A Baby… Rachel … Tamara… United… October 1…         2020 TV-PG 
##  9 s251    Movie A Walk… Adam Sh… Mandy … United… July 1, 2…         2002 PG    
## 10 s297    Movie Across… Julien … Sarah … Canada  April 1, …         2015 TV-MA 
## # … with 140 more rows, and 3 more variables: duration &lt;chr&gt;, listed_in &lt;chr&gt;,
## #   description &lt;chr&gt;</code></pre>
<div class="sourceCode" id="cb2160"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Manipulamos fechas</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://lubridate.tidyverse.org">lubridate</a></span><span class="op">)</span>
<span class="va">netflix_final</span> <span class="op">&lt;-</span> 
  <span class="va">netflix_hs</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/mutate.html">mutate</a></span><span class="op">(</span>year <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/lubridate/man/year.html">year</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/lubridate/man/ymd.html">mdy</a></span><span class="op">(</span><span class="va">date_added</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">year</span><span class="op">)</span><span class="op">)</span>

<span class="va">netflix_resumen</span> <span class="op">&lt;-</span> 
  <span class="va">netflix_final</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/group_by.html">group_by</a></span><span class="op">(</span><span class="va">year</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/count.html">count</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span>

<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/yixuan/sysfonts">sysfonts</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/yixuan/showtext">showtext</a></span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/sysfonts/man/font_add_google.html">font_add_google</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Bebas Neue"</span>, name <span class="op">=</span> <span class="st">"Bebas Neue"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/sysfonts/man/font_add_google.html">font_add_google</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Permanent Marker"</span>, name <span class="op">=</span> <span class="st">"Permanent Marker"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/showtext/man/showtext_auto.html">showtext_auto</a></span><span class="op">(</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">netflix_resumen</span>, <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">year</span>, y <span class="op">=</span> <span class="va">n</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_bar.html">geom_col</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>breaks <span class="op">=</span> <span class="va">netflix_resumen</span><span class="op">$</span><span class="va">year</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggtheme.html">theme_void</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/theme.html">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span>,
        plot.title <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Bebas Neue"</span>,
                                  color <span class="op">=</span> <span class="st">"red"</span>, size <span class="op">=</span> <span class="fl">80</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"NETFLIX"</span>,
       subtitle <span class="op">=</span> <span class="st">"Películas y series de instituto"</span>,
       caption <span class="op">=</span> <span class="st">"Basada en El Arte del Dato (https://elartedeldato.com) | Datos: Kaggle"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/theme.html">theme</a></span><span class="op">(</span>panel.background <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/element.html">element_rect</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span>,
        plot.background <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/element.html">element_rect</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"black"</span>, 
                                       color <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span>,
        panel.grid.major.y <span class="op">=</span>
          <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/element.html">element_line</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">0.1</span>, color <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span>,
        plot.subtitle <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Permanent Marker"</span>,
                                     size <span class="op">=</span> <span class="fl">21</span>, color <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span>,
        plot.caption <span class="op">=</span>  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Permanent Marker"</span>,
                                     color <span class="op">=</span> <span class="st">"white"</span>, size <span class="op">=</span> <span class="fl">19</span><span class="op">)</span>,
        axis.text <span class="op">=</span> 
          <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/element.html">element_text</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">15</span>, family <span class="op">=</span> <span class="st">"Permanent Marker"</span>,
                       color <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span>,
        plot.margin <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/element.html">margin</a></span><span class="op">(</span>t <span class="op">=</span> <span class="fl">4</span>, r <span class="op">=</span> <span class="fl">4</span>, b <span class="op">=</span> <span class="fl">4</span>, l <span class="op">=</span> <span class="fl">8</span>, <span class="st">"pt"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/annotate.html">annotate</a></span><span class="op">(</span><span class="st">"text"</span>, label <span class="op">=</span> <span class="st">"Moda"</span>, 
           x <span class="op">=</span> <span class="fl">2020.7</span>, y <span class="op">=</span> <span class="fl">47</span>, hjust <span class="op">=</span> <span class="fl">0.2</span>, vjust <span class="op">=</span> <span class="fl">0</span>, family <span class="op">=</span> <span class="st">"Permanent Marker"</span>, size <span class="op">=</span> <span class="fl">6</span>, color <span class="op">=</span> <span class="st">'white'</span>, angle <span class="op">=</span> <span class="fl">10</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/annotate.html">annotate</a></span><span class="op">(</span><span class="st">"curve"</span>, x <span class="op">=</span> <span class="fl">2020.3</span>, y <span class="op">=</span> <span class="fl">48</span>, xend <span class="op">=</span> <span class="fl">2020</span>, yend <span class="op">=</span> <span class="fl">44</span>,
           color <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="curso_R_ECI_files/figure-html/unnamed-chunk-888-1.png" width="768"></div>
<p>Para calcularla podemos usar el paquete <a href="https://github.com/paulponcet/modeest">modeest</a>: la función <code><a href="https://rdrr.io/pkg/statip/man/mfv.html">mfv()</a></code> nos calcula la <strong>moda exacta</strong> de una variable numérica discreta o cuantitativa (busca los valores más repetidos), la función <code><a href="https://rdrr.io/pkg/modeest/man/mlv.html">mlv()</a></code> nos calcula la <strong>moda estimada</strong> de una variable numérica continua.</p>
<div class="sourceCode" id="cb2161"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/paulponcet/modeest">modeest</a></span><span class="op">)</span>

<span class="co"># Media y mediana y moda de mass y n_films</span>
<span class="va">resumen</span> <span class="op">&lt;-</span> 
  <span class="va">starwars_nueva</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise</a></span><span class="op">(</span>media <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/across.html">across</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">mass</span>, <span class="va">n_films</span><span class="op">)</span>, <span class="va">mean</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            mediana <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/across.html">across</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">mass</span>, <span class="va">n_films</span><span class="op">)</span>, <span class="va">median</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            moda_n_films <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/statip/man/mfv.html">mfv</a></span><span class="op">(</span><span class="va">n_films</span>, na_rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            moda_mass <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/modeest/man/mlv.html">mlv</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span>
<span class="va">resumen</span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##   media$mass $n_films mediana$mass $n_films moda_n_films moda_mass
##        &lt;dbl&gt;    &lt;dbl&gt;        &lt;dbl&gt;    &lt;int&gt;        &lt;int&gt;     &lt;dbl&gt;
## 1       97.3     1.99           79        1            1      80.3</code></pre>
<p>Fíjate que el resumen ha agrupado todas las modas y medianas que hemos calculado a la vez: <strong>la salida de nuestro resumen es una lista, con tablas a su vez dentro</strong>.</p>
<p> </p>
<p>Veamos un ejemplo sintético de <mark><strong>distribuciones multimodales</strong></mark>, generando con <code><a href="https://rdrr.io/r/stats/Normal.html">rnorm()</a></code> (genera datos aleatorias provenientes de una distribución normal) un conjunto <mark><strong>unimodal</strong></mark>, <mark><strong>bimodal</strong></mark> y <mark><strong>trimodal</strong></mark>, los 3 con la misma media.</p>
<div class="sourceCode" id="cb2163"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">n</span> <span class="op">&lt;-</span> <span class="fl">900</span>

<span class="co"># Datos</span>
<span class="va">datos</span> <span class="op">&lt;-</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tibble/man/tibble.html">tibble</a></span><span class="op">(</span><span class="st">"unimod"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span>, <span class="fl">5</span>, <span class="fl">1</span><span class="op">)</span>,
         <span class="st">"bimod"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span><span class="op">/</span><span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">1</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span><span class="op">/</span><span class="fl">2</span>, <span class="fl">7</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span>,
         <span class="st">"trimod"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span><span class="op">/</span><span class="fl">3</span>, <span class="fl">2</span>, <span class="fl">1</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span><span class="op">/</span><span class="fl">3</span>, <span class="fl">5</span>, <span class="fl">1</span><span class="op">)</span>,
                      <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span><span class="op">/</span><span class="fl">3</span>, <span class="fl">8</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>

<span class="co"># Tidy data</span>
<span class="va">datos</span> <span class="op">&lt;-</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tidyr/man/pivot_longer.html">pivot_longer</a></span><span class="op">(</span><span class="va">datos</span>, cols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/tidyselect/man/everything.html">everything</a></span><span class="op">(</span><span class="op">)</span>,
               names_to <span class="op">=</span> <span class="st">"tipo"</span>, values_to <span class="op">=</span> <span class="st">"values"</span><span class="op">)</span>

<span class="co"># Estadisticas</span>
<span class="va">datos</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/group_by.html">group_by</a></span><span class="op">(</span><span class="va">tipo</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise</a></span><span class="op">(</span>media <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">values</span><span class="op">)</span>,
            mediana <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">values</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 3
##   tipo   media mediana
##   &lt;chr&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1 bimod   5.00    5.14
## 2 trimod  5.00    5.05
## 3 unimod  4.94    4.94</code></pre>
<p>Sólo utilizando la media estos casos son indistiguibles, ya que en todos los casos la media y mediana coinciden, pero si podemos hacerlo visualizando sus densidades.</p>
<div class="sourceCode" id="cb2165"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://wilkelab.org/ggridges/">ggridges</a></span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">datos</span>,
       <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">tipo</span>, x <span class="op">=</span> <span class="va">values</span>, fill <span class="op">=</span> <span class="va">tipo</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggridges/man/geom_density_ridges.html">geom_density_ridges</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.7</span>, height <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/MetBrewer/man/met.brewer.html">met.brewer</a></span><span class="op">(</span><span class="st">"Klimt"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/labs.html">labs</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"Distribución"</span>,
       y <span class="op">=</span> <span class="st">"Distribución"</span>,
       title <span class="op">=</span> <span class="st">"DISTRIBUCIONES MULTIMODALES"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="curso_R_ECI_files/figure-html/unnamed-chunk-891-1.png" width="768"></div>
<p>Con <code><a href="https://rdrr.io/pkg/ggridges/man/stat_density_ridges.html">stat_density_ridges()</a></code> podemos además marcar algunos valores, como por ejemplo los cuartiles.</p>
<div class="sourceCode" id="cb2166"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">datos</span>,
       <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">tipo</span>, x <span class="op">=</span> <span class="va">values</span>, fill <span class="op">=</span> <span class="va">tipo</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggridges/man/geom_density_ridges.html">geom_density_ridges</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.7</span>, height <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggridges/man/stat_density_ridges.html">stat_density_ridges</a></span><span class="op">(</span>quantile_lines <span class="op">=</span> <span class="cn">TRUE</span>,
                      quantiles <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span><span class="op">)</span>,
                      color <span class="op">=</span> <span class="st">"black"</span>, alpha <span class="op">=</span> <span class="fl">.8</span>,
                      size <span class="op">=</span> <span class="fl">0.7</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/MetBrewer/man/met.brewer.html">met.brewer</a></span><span class="op">(</span><span class="st">"Klimt"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/labs.html">labs</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"Distribución"</span>,
       y <span class="op">=</span> <span class="st">"Distribución"</span>,
       title <span class="op">=</span> <span class="st">"DISTRIBUCIONES MULTIMODALES"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="curso_R_ECI_files/figure-html/unnamed-chunk-892-1.png" width="768"></div>
<p>De la misma manera podemos pedirle que nos calcule <mark><strong>medidas de dispersión (varianza, desv. típica y cv)</strong></mark>, que nos indican cómo de dispersos están los datos respecto a un centro, normalmente la media, y <mark><strong>medidas de localización (percentiles)</strong></mark> (valores que nos parten los datos en trozos iguales). Dada una proporción de los datos <span class="math inline">\(0 &lt; p &lt; 1\)</span>, el <mark><strong>cuantil de orden <span class="math inline">\(p\)</span></strong></mark> de una variable cuantitativa, denotado como <span class="math inline">\(Q_p\)</span>, es el valor más pequeño tal que su frecuencia relativa acumulada es mayor o igual que <span class="math inline">\(p\)</span>: es el número más pequeño que deja a su izquierda (incluyéndolo a él) como mínimo la fracción <span class="math inline">\(p\)</span> de los datos (la propia mediana es el cuantil <span class="math inline">\(Q_{0.5}\)</span>.</p>
<div class="sourceCode" id="cb2167"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise</a></span><span class="op">(</span>media <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            mediana <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            moda <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/modeest/man/mlv.html">mlv</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            var <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">var</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            cv <span class="op">=</span> <span class="va">sd</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">media</span><span class="op">)</span>,
            p13 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">mass</span>, probs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.13</span><span class="op">)</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            p87 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">mass</span>, probs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.87</span><span class="op">)</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 8
##   media mediana  moda    var    sd    cv   p13   p87
##   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  97.3      79  80.3 28716.  169.  1.74  46.6  111.</code></pre>
<p>Haciendo uso de cosas ya vistas podemos, por ejemplo, <mark><strong>calcular el coeficiente de variación (CV)</strong></mark> de todas las variables numéricas para poder decidir cual es más o menos dispersa.</p>
<div class="sourceCode" id="cb2169"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">resumen</span> <span class="op">&lt;-</span> 
  <span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise</a></span><span class="op">(</span>media <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/across.html">across</a></span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span>, <span class="va">mean</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            var <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/across.html">across</a></span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span>, <span class="va">var</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            cv <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">var</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">media</span><span class="op">)</span><span class="op">)</span>
<span class="va">resumen</span><span class="op">$</span><span class="va">media</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   height  mass birth_year
##    &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
## 1   174.  97.3       87.6</code></pre>
<div class="sourceCode" id="cb2171"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">resumen</span><span class="op">$</span><span class="va">var</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   height   mass birth_year
##    &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;
## 1  1209. 28716.     23929.</code></pre>
<div class="sourceCode" id="cb2173"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">resumen</span><span class="op">$</span><span class="va">cv</span> <span class="co"># más homogénea la altura por tener menos CV.</span></code></pre></div>
<pre><code>##      height     mass birth_year
## 1 0.1994197 1.741382   1.766587</code></pre>
</div>
<div id="agrupando-datos-group_by" class="section level3">
<h3>
<span class="header-section-number">25.1.2</span> Agrupando datos: group_by<a class="anchor" aria-label="anchor" href="#agrupando-datos-group_by"><i class="fas fa-link"></i></a>
</h3>
<p>Una de las funcionalidades más potentes es la opción de <mark><strong>añadir antes una agrupación</strong></mark> con <code><a href="https://rdrr.io/pkg/dplyr/man/group_by.html">group_by()</a></code>. Esta función per se no cambia los datos sino que cambia la forma en la que se aplicarán las funciones posteriores, realizándose por <strong>desagregadas grupos</strong>.</p>
<p>Imagina que queremos calcular la <strong>media de altura y peso</strong> de cada personaje PERO desagregada por cada una de las clases que tenemos en la variable <code>sex</code>.</p>
<div class="sourceCode" id="cb2175"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/group_by.html">group_by</a></span><span class="op">(</span><span class="va">sex</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise</a></span><span class="op">(</span>media_altura <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">height</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            media_peso <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 5 × 3
##   sex            media_altura media_peso
##   &lt;chr&gt;                 &lt;dbl&gt;      &lt;dbl&gt;
## 1 female                 169.       54.7
## 2 hermaphroditic         175      1358  
## 3 male                   179.       81.0
## 4 none                   131.       69.8
## 5 &lt;NA&gt;                   181.       48</code></pre>
<p>Lo que obtenemos no es la media de todos los personajes sino la <strong>media desagregada por grupo</strong>, grupo marcado por la variable <code>sex</code>. Las <strong>agrupaciones pueden estar en función de varias variables</strong> a la vez.</p>
<div class="sourceCode" id="cb2177"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/group_by.html">group_by</a></span><span class="op">(</span><span class="va">sex</span>, <span class="va">gender</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise</a></span><span class="op">(</span>media_altura <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">height</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            media_peso <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mass</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
##   sex            gender    media_altura media_peso
##   &lt;chr&gt;          &lt;chr&gt;            &lt;dbl&gt;      &lt;dbl&gt;
## 1 female         feminine          169.       54.7
## 2 hermaphroditic masculine         175      1358  
## 3 male           masculine         179.       81.0
## 4 none           feminine           96       NaN  
## 5 none           masculine         140        69.8
## 6 &lt;NA&gt;           &lt;NA&gt;              181.       48</code></pre>
<p>Dicha función también es muy útil cuando queremos <strong>realizar un filtro de registros en base al número de cada clase</strong>: por ejemplo, vamos a filtrar los registros que pertenezcan a una clase de <code>sex</code> que tenga al menos 10 individuos dentro de dicho grupo.</p>
<div class="sourceCode" id="cb2179"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/group_by.html">group_by</a></span><span class="op">(</span><span class="va">sex</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/count.html">count</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 5 × 2
##   sex                n
##   &lt;chr&gt;          &lt;int&gt;
## 1 female            16
## 2 hermaphroditic     1
## 3 male              60
## 4 none               6
## 5 &lt;NA&gt;               4</code></pre>
<p>Si te fijas solo deberíamos filtrar los registros que sean <code>female</code> y <code>male</code>. Vamos a hacerlo de forma automática en base a dicho <strong>umbral</strong>.</p>
<div class="sourceCode" id="cb2181"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Podemos filtrar por grupos solo aquellos que superen un</span>
<span class="co"># un umbral mínimo</span>
<span class="va">starwars</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/group_by.html">group_by</a></span><span class="op">(</span><span class="va">sex</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/context.html">n</a></span><span class="op">(</span><span class="op">)</span> <span class="op">&gt;</span> <span class="fl">10</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 76 × 14
##    name    height  mass hair_color  skin_color eye_color birth_year sex   gender
##    &lt;chr&gt;    &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
##  1 Luke S…    172    77 blond       fair       blue            19   male  mascu…
##  2 Darth …    202   136 none        white      yellow          41.9 male  mascu…
##  3 Leia O…    150    49 brown       light      brown           19   fema… femin…
##  4 Owen L…    178   120 brown, grey light      blue            52   male  mascu…
##  5 Beru W…    165    75 brown       light      blue            47   fema… femin…
##  6 Biggs …    183    84 black       light      brown           24   male  mascu…
##  7 Obi-Wa…    182    77 auburn, wh… fair       blue-gray       57   male  mascu…
##  8 Anakin…    188    84 blond       fair       blue            41.9 male  mascu…
##  9 Wilhuf…    180    NA auburn, gr… fair       blue            64   male  mascu…
## 10 Chewba…    228   112 brown       unknown    blue           200   male  mascu…
## # … with 66 more rows, and 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;,
## #   films &lt;list&gt;, vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
<p>Para comprobar rápidamente que efectivamente solo ha filtrado aquellos grupos con más de 10 elementos en ellos podemos <strong>añadir <code><a href="https://rdrr.io/pkg/dplyr/man/count.html">count()</a></code></strong>.</p>
<div class="sourceCode" id="cb2183"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/group_by.html">group_by</a></span><span class="op">(</span><span class="va">sex</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/context.html">n</a></span><span class="op">(</span><span class="op">)</span> <span class="op">&gt;</span> <span class="fl">10</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/count.html">count</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   sex        n
##   &lt;chr&gt;  &lt;int&gt;
## 1 female    16
## 2 male      60</code></pre>
<p>Los resúmenes y las agrupaciones podemos <strong>combinarlas de todas las formas que nos imaginemos</strong>, por ejemplo, calculando la media desagregada por sexo y género pero solo de las variables numéricas.</p>
<div class="sourceCode" id="cb2185"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span> <span class="co"># doble agrupación</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/group_by.html">group_by</a></span><span class="op">(</span><span class="va">sex</span>, <span class="va">gender</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/across.html">across</a></span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span>, <span class="va">mean</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
##   sex            gender    height   mass birth_year
##   &lt;chr&gt;          &lt;chr&gt;      &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;
## 1 female         feminine    169.   54.7       47.2
## 2 hermaphroditic masculine   175  1358        600  
## 3 male           masculine   179.   81.0       85.5
## 4 none           feminine     96   NaN        NaN  
## 5 none           masculine   140    69.8       53.3
## 6 &lt;NA&gt;           &lt;NA&gt;        181.   48         62</code></pre>
</div>
<div id="rowwise-operaciones-por-filas" class="section level3">
<h3>
<span class="header-section-number">25.1.3</span> Rowwise: operaciones por filas<a class="anchor" aria-label="anchor" href="#rowwise-operaciones-por-filas"><i class="fas fa-link"></i></a>
</h3>
<p>Por último veamos un ejemplo de una <strong>opción muy útil usada antes de una operación que es</strong> <code><a href="https://rdrr.io/pkg/dplyr/man/rowwise.html">rowwise()</a></code>: toda operación que venga después se aplicará <mark><strong>en cada fila por separado</strong></mark>. Para el ejemplo vamos a definir un fichero <em>dummy</em> de notas en mates, lengua y dibujo de 50 alumnos. Para ello usamos la función <code><a href="https://rdrr.io/r/base/sample.html">sample()</a></code>: le decimos que seleccione aleatoriamente <code>size = 50</code> notas de un conjunto de notas posibles (<code>0:10</code>), y que lo haga con reemplazamiento (<code>replace = TRUE</code>, es decir, que dos alumnos puedan tener la misma nota)</p>
<div class="sourceCode" id="cb2187"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">notas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tibble/man/tibble.html">tibble</a></span><span class="op">(</span><span class="st">"mates"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="fl">10</span>, size <span class="op">=</span> <span class="fl">50</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
                <span class="st">"lengua"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="fl">10</span>, size <span class="op">=</span> <span class="fl">50</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
                <span class="st">"dibujo"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="fl">10</span>, size <span class="op">=</span> <span class="fl">50</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span>
<span class="va">notas</span></code></pre></div>
<pre><code>## # A tibble: 50 × 3
##    mates lengua dibujo
##    &lt;int&gt;  &lt;int&gt;  &lt;int&gt;
##  1     3     10      7
##  2     0      3      6
##  3     9      6      3
##  4     1      7      1
##  5     1      0      1
##  6     3     10      6
##  7     4      4     10
##  8     0      9      4
##  9     8      2      0
## 10     2      3     10
## # … with 40 more rows</code></pre>
<p>Una vez que tenemos 3 notas aleatorias por cada uno de los 50 alumnos, <strong>¿qué sucede si yo quiero calcular la nota media del curso?</strong></p>
<div class="sourceCode" id="cb2189"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">notas</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/mutate.html">mutate</a></span><span class="op">(</span>media_curso <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">mates</span>, <span class="va">lengua</span>, <span class="va">dibujo</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 50 × 4
##    mates lengua dibujo media_curso
##    &lt;int&gt;  &lt;int&gt;  &lt;int&gt;       &lt;dbl&gt;
##  1     3     10      7        4.77
##  2     0      3      6        4.77
##  3     9      6      3        4.77
##  4     1      7      1        4.77
##  5     1      0      1        4.77
##  6     3     10      6        4.77
##  7     4      4     10        4.77
##  8     0      9      4        4.77
##  9     8      2      0        4.77
## 10     2      3     10        4.77
## # … with 40 more rows</code></pre>
<p>Como ves si aplicamos la media de las tres variables, en cada fila el valor de <code>media_curso</code> es idéntico ya que nos ha hecho la <strong>media global</strong>: ha tomado las 50 filas, las 3 columnas, y ha hecho la media de 150 datos. Cuando en realidad a nosotros nos gustaría <strong>sacar una media por registro</strong>, que para cada alumno tengamos la media de las asignaturas.</p>
<div class="sourceCode" id="cb2191"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Aplicado por fila</span>
<span class="va">notas</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/rowwise.html">rowwise</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/mutate.html">mutate</a></span><span class="op">(</span>media_curso <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">mates</span>, <span class="va">lengua</span>, <span class="va">dibujo</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 50 × 4
## # Rowwise: 
##    mates lengua dibujo media_curso
##    &lt;int&gt;  &lt;int&gt;  &lt;int&gt;       &lt;dbl&gt;
##  1     3     10      7       6.67 
##  2     0      3      6       3    
##  3     9      6      3       6    
##  4     1      7      1       3    
##  5     1      0      1       0.667
##  6     3     10      6       6.33 
##  7     4      4     10       6    
##  8     0      9      4       4.33 
##  9     8      2      0       3.33 
## 10     2      3     10       5    
## # … with 40 more rows</code></pre>
<p>Solos nos falta poner la guinda a lo aprendido a esta introducción: vamos a ver como podemos <mark><strong>relacionar dos conjuntos de datos distintos entre sí</strong></mark>.</p>
</div>
</div>
<div id="relacionar-datos-joins" class="section level2">
<h2>
<span class="header-section-number">25.2</span> Relacionar datos (joins)<a class="anchor" aria-label="anchor" href="#relacionar-datos-joins"><i class="fas fa-link"></i></a>
</h2>
<p>Una de las <strong>opciones más comunes para trabajar con datos</strong> es tener a nuestra disposición diversas tablas, con alguno o varios de los campos en común, y nos interesa a veces <mark><strong>cruzar datos</strong></mark> de ambos para tener una información más completa con el conjunto de las tablas. Es lo que se conoce en ciencia de datos e informática como <strong>hacer un <em>join</em> de tablas</strong>. Para ese cruce será <strong>indispensable que haya uno o varios campos clave</strong>, campos que sirvan para identificar unívocamente cada registro (por ejemplo, DNI).</p>
<div class="figure">
<span style="display:block;" id="fig:joins"></span>
<img src="img/sql-joins.jpg" alt="Esquema con los principales tipos de join, extraído de &lt;https://estradawebgroup.com/Post/-Que-es-y-para-que-sirve-SQL-Joins-/4278&gt;" width="450"><p class="caption">
Imagen/gráfica 25.1: Esquema con los principales tipos de join, extraído de <a href="https://estradawebgroup.com/Post/-Que-es-y-para-que-sirve-SQL-Joins-/4278" class="uri">https://estradawebgroup.com/Post/-Que-es-y-para-que-sirve-SQL-Joins-/4278</a>
</p>
</div>
<p>Existen principalmente <strong>cuatro tipos de cruces</strong> si pensamos en cruzar un conjunto <code>A</code> con otro conjunto <code>B</code>:</p>
<ul>
<li><p><strong>Inner join</strong>: solo nos quedamos con las <strong>filas que tengan correspondencia en ambas tablas</strong> (personas cuyo DNI aparezca en ambas tablas, por ejemplo).</p></li>
<li><p><strong>Left (outer) join</strong>: nos quedamos con <strong>todas las filas de <code>A</code></strong>, buscando que registros de dicha tabla están también en <code>B</code>, completando los datos de esta tabla para esos registros.</p></li>
<li><p><strong>Right (outer) join</strong>: nos quedamos con <strong>todas las filas de <code>B</code></strong>, buscando que registros de dicha tabla están también en <code>A</code>, completando los datos de esta tabla para esos registros.</p></li>
<li><p><strong>Full join</strong>: nos quedamos con <strong>todas las filas de <code>A</code> y <code>B</code></strong>, tengan o no correspondencia en la otra tabla (si no está en una de ellas, las columnas correspondientes quedarán como campo ausente).</p></li>
</ul>
<p>Esos <strong>campos clave (keys)</strong> serán las columnas que usaremos para definir los cruces. Para los ejemplos usaremos las tablas del paquete <a href="https://github.com/hadley/nycflights13">nycflights13</a>.</p>
<div class="sourceCode" id="cb2193"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/hadley/nycflights13">nycflights13</a></span><span class="op">)</span></code></pre></div>
<p>Dicho paquete cuenta con las siguientes <strong>tablas</strong>:</p>
<ul>
<li>
<code>airlines</code>: nombre de la aerolínea (con su abreviatura).</li>
<li>
<code>airports</code>: datos de aeropuertos (nombres, longitud, latitud, altitud, etc).</li>
<li>
<code>flights</code>: datos de vuelos (con <code>tailnum</code> como marca de idenfiticación).</li>
<li>
<code>planes</code>: datos de los aviones.</li>
<li>
<code>weather</code>: datos meteorológicos horarios de las estaciones LGA, JFK y EWR.</li>
</ul>
<p>Veamos un ejemplo: imagina que queremos <strong>completar en la tabla de vuelos los datos de cada una de las aerolíneas que operan dichos vuelos</strong>. Vamos a seleccionar unas pocas columnas para que sea más fácil de visualizar.</p>
<div class="sourceCode" id="cb2194"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Seleccionamos antes columnas para que sea más corto</span>
<span class="va">flights_filtrada</span> <span class="op">&lt;-</span> <span class="va">flights</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/select.html">select</a></span><span class="op">(</span><span class="va">year</span><span class="op">:</span><span class="va">day</span>, <span class="va">arr_time</span>, <span class="va">carrier</span><span class="op">:</span><span class="va">dest</span><span class="op">)</span>
<span class="va">flights_filtrada</span></code></pre></div>
<pre><code>## # A tibble: 336,776 × 9
##     year month   day arr_time carrier flight tailnum origin dest 
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt; &lt;chr&gt;    &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;
##  1  2013     1     1      830 UA        1545 N14228  EWR    IAH  
##  2  2013     1     1      850 UA        1714 N24211  LGA    IAH  
##  3  2013     1     1      923 AA        1141 N619AA  JFK    MIA  
##  4  2013     1     1     1004 B6         725 N804JB  JFK    BQN  
##  5  2013     1     1      812 DL         461 N668DN  LGA    ATL  
##  6  2013     1     1      740 UA        1696 N39463  EWR    ORD  
##  7  2013     1     1      913 B6         507 N516JB  EWR    FLL  
##  8  2013     1     1      709 EV        5708 N829AS  LGA    IAD  
##  9  2013     1     1      838 B6          79 N593JB  JFK    MCO  
## 10  2013     1     1      753 AA         301 N3ALAA  LGA    ORD  
## # … with 336,766 more rows</code></pre>
<p>Queremos <strong>TODAS las filas de los vuelos</strong>, todos sus registros, pero <strong>añadiendo la información</strong> que tenemos de la aerolínea que opere los vuelos, así que haremos un <strong>LEFT JOIN</strong> de <code>flights</code> vs <code>airlines</code>. El campo común que nos permite cruzarla, la <strong>clave (key)</strong> es el código abreviado de las aerolíneas (variable <code>carrier</code>).</p>
<div class="sourceCode" id="cb2196"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Mismas filas pero con una nueva columna: siempre que sea</span>
<span class="co"># posible el cruce tendrá la info de la aerolínea</span>
<span class="va">l_join_flights_airlines</span> <span class="op">&lt;-</span>
  <span class="va">flights_filtrada</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">airlines</span>, by <span class="op">=</span> <span class="st">"carrier"</span><span class="op">)</span>
<span class="va">l_join_flights_airlines</span></code></pre></div>
<pre><code>## # A tibble: 336,776 × 10
##     year month   day arr_time carrier flight tailnum origin dest  name          
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt; &lt;chr&gt;    &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;         
##  1  2013     1     1      830 UA        1545 N14228  EWR    IAH   United Air Li…
##  2  2013     1     1      850 UA        1714 N24211  LGA    IAH   United Air Li…
##  3  2013     1     1      923 AA        1141 N619AA  JFK    MIA   American Airl…
##  4  2013     1     1     1004 B6         725 N804JB  JFK    BQN   JetBlue Airwa…
##  5  2013     1     1      812 DL         461 N668DN  LGA    ATL   Delta Air Lin…
##  6  2013     1     1      740 UA        1696 N39463  EWR    ORD   United Air Li…
##  7  2013     1     1      913 B6         507 N516JB  EWR    FLL   JetBlue Airwa…
##  8  2013     1     1      709 EV        5708 N829AS  LGA    IAD   ExpressJet Ai…
##  9  2013     1     1      838 B6          79 N593JB  JFK    MCO   JetBlue Airwa…
## 10  2013     1     1      753 AA         301 N3ALAA  LGA    ORD   American Airl…
## # … with 336,766 more rows</code></pre>
<p>Si te fijas ahora tenemos en <code>l_join_flights_airlines</code> las mismas 336776 filas pero con una columna más: la tabla <code>airlines</code> tenía 2 columnas, una la común con <code>flights</code> y en otra la nueva que se ha incorporado a la tabla. <strong>¿Y si en <code>flights</code> había algún vuelo operado por alguna aerolínea que no estuviese en <code>airlines</code>?</strong></p>
<div class="sourceCode" id="cb2198"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Filtramos</span>
<span class="va">l_join_flights_airlines</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">name</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 0 × 10
## # … with 10 variables: year &lt;int&gt;, month &lt;int&gt;, day &lt;int&gt;, arr_time &lt;int&gt;,
## #   carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;,
## #   name &lt;chr&gt;</code></pre>
<p>En este caso todos los registros de la primera tabla tenían su correspondencia en la segunda tabla. Veamos un ejemplo donde suceda eso, quitándole algunas filas a <code>airlines</code>, quitando las aerolíneas con códigos <code>"B6"</code>.</p>
<div class="sourceCode" id="cb2200"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">airlines_filtrada</span> <span class="op">&lt;-</span> <span class="va">airlines</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="op">(</span><span class="va">carrier</span> <span class="op">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"B6"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="va">l_join</span> <span class="op">&lt;-</span> <span class="va">flights_filtrada</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">airlines_filtrada</span>, by <span class="op">=</span> <span class="st">"carrier"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">l_join</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">name</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 54635    10</code></pre>
<p>En el anterior ejemplo tenemos 54 635 filas que cuyo nombre está ausente, es decir, 54 635 filas de <code>flights</code> que no tienen correspondencia en la tabla filtrada <code>airlines_filtrada</code>. Ahora las <strong>filas que no han encontrado su <em>match</em> en la segunda tabla están como campo ausente</strong>.</p>
<div class="sourceCode" id="cb2202"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">l_join</span></code></pre></div>
<pre><code>## # A tibble: 336,776 × 10
##     year month   day arr_time carrier flight tailnum origin dest  name          
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt; &lt;chr&gt;    &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;         
##  1  2013     1     1      830 UA        1545 N14228  EWR    IAH   United Air Li…
##  2  2013     1     1      850 UA        1714 N24211  LGA    IAH   United Air Li…
##  3  2013     1     1      923 AA        1141 N619AA  JFK    MIA   American Airl…
##  4  2013     1     1     1004 B6         725 N804JB  JFK    BQN   &lt;NA&gt;          
##  5  2013     1     1      812 DL         461 N668DN  LGA    ATL   Delta Air Lin…
##  6  2013     1     1      740 UA        1696 N39463  EWR    ORD   United Air Li…
##  7  2013     1     1      913 B6         507 N516JB  EWR    FLL   &lt;NA&gt;          
##  8  2013     1     1      709 EV        5708 N829AS  LGA    IAD   ExpressJet Ai…
##  9  2013     1     1      838 B6          79 N593JB  JFK    MCO   &lt;NA&gt;          
## 10  2013     1     1      753 AA         301 N3ALAA  LGA    ORD   American Airl…
## # … with 336,766 more rows</code></pre>
<div class="figure">
<span style="display:block;" id="fig:left-join"></span>
<img src="img/left_join.jpg" alt="Esquema del left join, extraído de &lt;https://r4ds.had.co.nz/relational-data.html#mutating-joins&gt;" width="400"><p class="caption">
Imagen/gráfica 25.2: Esquema del left join, extraído de <a href="https://r4ds.had.co.nz/relational-data.html#mutating-joins" class="uri">https://r4ds.had.co.nz/relational-data.html#mutating-joins</a>
</p>
</div>
<p>La misma lógica para los <strong>RIGHT JOIN</strong> y los <strong>FULL JOIN</strong>. En este último tendremos bastantes datos ausentes, ya que todos los registros que no estén en ambas tablas tendrán una parte de sus variables como <code>NA</code></p>
<div class="sourceCode" id="cb2204"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tabla1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tibble/man/tibble.html">tibble</a></span><span class="op">(</span><span class="st">"key_1"</span> <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">7</span>, <span class="st">"valor_1"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"x"</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">7</span><span class="op">)</span><span class="op">)</span>
<span class="va">tabla2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tibble/man/tibble.html">tibble</a></span><span class="op">(</span><span class="st">"key_2"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">5</span>, <span class="fl">6</span>, <span class="fl">9</span>, <span class="fl">10</span><span class="op">)</span>,
                 <span class="st">"valor_2"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"x"</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">5</span>, <span class="fl">6</span>, <span class="fl">9</span>, <span class="fl">10</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>

<span class="co"># Left</span>
<span class="va">tabla1</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">tabla2</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"key_1"</span> <span class="op">=</span> <span class="st">"key_2"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 7 × 3
##   key_1 valor_1 valor_2
##   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;  
## 1     1 x1      x1     
## 2     2 x2      x2     
## 3     3 x3      &lt;NA&gt;   
## 4     4 x4      &lt;NA&gt;   
## 5     5 x5      x5     
## 6     6 x6      x6     
## 7     7 x7      &lt;NA&gt;</code></pre>
<div class="sourceCode" id="cb2206"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Right</span>
<span class="va">tabla1</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/mutate-joins.html">right_join</a></span><span class="op">(</span><span class="va">tabla2</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"key_1"</span> <span class="op">=</span> <span class="st">"key_2"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 7 × 3
##   key_1 valor_1 valor_2
##   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;  
## 1     1 x1      x1     
## 2     2 x2      x2     
## 3     5 x5      x5     
## 4     6 x6      x6     
## 5     0 &lt;NA&gt;    x0     
## 6     9 &lt;NA&gt;    x9     
## 7    10 &lt;NA&gt;    x10</code></pre>
<div class="sourceCode" id="cb2208"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Full</span>
<span class="va">tabla1</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/mutate-joins.html">full_join</a></span><span class="op">(</span><span class="va">tabla2</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"key_1"</span> <span class="op">=</span> <span class="st">"key_2"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 10 × 3
##    key_1 valor_1 valor_2
##    &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;  
##  1     1 x1      x1     
##  2     2 x2      x2     
##  3     3 x3      &lt;NA&gt;   
##  4     4 x4      &lt;NA&gt;   
##  5     5 x5      x5     
##  6     6 x6      x6     
##  7     7 x7      &lt;NA&gt;   
##  8     0 &lt;NA&gt;    x0     
##  9     9 &lt;NA&gt;    x9     
## 10    10 &lt;NA&gt;    x10</code></pre>
<div class="figure">
<span style="display:block;" id="fig:right-join"></span>
<img src="img/right_join.jpg" alt="Esquema del right join, extraído de &lt;https://r4ds.had.co.nz/relational-data.html#mutating-joins&gt;" width="400"><p class="caption">
Imagen/gráfica 25.3: Esquema del right join, extraído de <a href="https://r4ds.had.co.nz/relational-data.html#mutating-joins" class="uri">https://r4ds.had.co.nz/relational-data.html#mutating-joins</a>
</p>
</div>
<div class="figure">
<span style="display:block;" id="fig:full-join"></span>
<img src="img/full_join.jpg" alt="Esquema del full join, extraído de &lt;https://r4ds.had.co.nz/relational-data.html#mutating-joins&gt;" width="400"><p class="caption">
Imagen/gráfica 25.4: Esquema del full join, extraído de <a href="https://r4ds.had.co.nz/relational-data.html#mutating-joins" class="uri">https://r4ds.had.co.nz/relational-data.html#mutating-joins</a>
</p>
</div>
<p>Un tipo de join especial son los <strong>INNER JOIN</strong>. Hasta ahora la tabla resultante tenía al menos tantas filas como tuviese la tabla más pequeña en el cruce. En el caso de los <strong>INNER JOIN</strong> vamos a <strong>reducir el tamaño</strong> ya que solo nos quedaremos con <strong>aquellos registros que podamos encontrar en ambas</strong>, de forma que <strong>el cruce nunca generará datos ausentes</strong>.</p>
<div class="sourceCode" id="cb2210"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Inner</span>
<span class="va">tabla1</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/mutate-joins.html">inner_join</a></span><span class="op">(</span><span class="va">tabla2</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"key_1"</span> <span class="op">=</span> <span class="st">"key_2"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 4 × 3
##   key_1 valor_1 valor_2
##   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;  
## 1     1 x1      x1     
## 2     2 x2      x2     
## 3     5 x5      x5     
## 4     6 x6      x6</code></pre>
<div class="figure">
<span style="display:block;" id="fig:inner-join"></span>
<img src="img/inner_join.png" alt="Esquema del inner join, extraído de &lt;https://r4ds.had.co.nz/relational-data.html#mutating-joins&gt;" width="338"><p class="caption">
Imagen/gráfica 25.5: Esquema del inner join, extraído de <a href="https://r4ds.had.co.nz/relational-data.html#mutating-joins" class="uri">https://r4ds.had.co.nz/relational-data.html#mutating-joins</a>
</p>
</div>
</div>
<div id="ejercicios-16" class="section level2">
<h2>
<span class="header-section-number">25.3</span> 📝 Ejercicios<a class="anchor" aria-label="anchor" href="#ejercicios-16"><i class="fas fa-link"></i></a>
</h2>
<p>en construcción (cuarteto de anscombe)</p>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="descriptiva_cuantitativas.html"><span class="header-section-number">24</span> Extrayendo información: estadística descriptiva con cuantitativas continuas</a></div>
<div class="next"><a href="bibliograf%C3%ADa.html">Bibliografía</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#resumenes"><span class="header-section-number">25</span> Resumiendo y relacionado datos</a></li>
<li>
<a class="nav-link" href="#res%C3%BAmenes-num%C3%A9ricos-summarise-y-skimr-y-por-grupos-group_by"><span class="header-section-number">25.1</span> Resúmenes numéricos (summarise y skimr) y por grupos (group_by)</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#medidas-de-centralizaci%C3%B3n-y-dispersi%C3%B3n"><span class="header-section-number">25.1.1</span> Medidas de centralización y dispersión</a></li>
<li><a class="nav-link" href="#agrupando-datos-group_by"><span class="header-section-number">25.1.2</span> Agrupando datos: group_by</a></li>
<li><a class="nav-link" href="#rowwise-operaciones-por-filas"><span class="header-section-number">25.1.3</span> Rowwise: operaciones por filas</a></li>
</ul>
</li>
<li><a class="nav-link" href="#relacionar-datos-joins"><span class="header-section-number">25.2</span> Relacionar datos (joins)</a></li>
<li><a class="nav-link" href="#ejercicios-16"><span class="header-section-number">25.3</span> 📝 Ejercicios</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/dadosdelaplace/courses-ECI-2022/blob/master/25-resumenes.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/dadosdelaplace/courses-ECI-2022/edit/master/25-resumenes.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Analizando datos, visualizando información, contando historias</strong>" was written by Javier Álvarez Liébana y Gabriel Valverde Castilla. It was last built on Última actualización: 30-01-2022.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
